# Site settings
title: Peter Soderberg
email: PTSoderberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learnign to Code at Dev Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: PTSoderberg
github_username:  psoderberg

# Build settings
markdown: kramdown
