# Site settings
title: Peter Soderberg
email: PTSoderberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code at Dev Bootcamp
baseurl: "/PTS-site" # the subpath of your site, e.g. /blog/
url: "http://psoderberg.github.io" # the base hostname & protocol for your site
twitter_username: PTSoderberg
github_username:  psoderberg

# Build settings
markdown: kramdown
